from enum import Enum

class AgentStatus(str, Enum):
    OFFLINE = "OFFLINE"
    AVAILABLE = "AVAILABLE"
    RESERVED = "RESERVED"
    DIALING = "DIALING"
    CONNECTED = "CONNECTED"
    WRAP_UP = "WRAP_UP"
    PAUSED = "PAUSED"

class CallStatus(str, Enum):
    QUEUED = "QUEUED"
    RESERVED = "RESERVED"
    INITIATED = "INITIATED"
    RINGING = "RINGING"
    ANSWERED = "ANSWERED"
    AWAITING_AGENT = "AWAITING_AGENT"
    CONNECTED = "CONNECTED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    ABANDONED = "ABANDONED"

TERMINAL_CALL_STATUSES = {CallStatus.COMPLETED, CallStatus.FAILED, CallStatus.CANCELLED, CallStatus.ABANDONED}

class AllocationMode(str, Enum):
    AGENT_BOUND = "AGENT_BOUND"
    PREDICTIVE_UNASSIGNED = "PREDICTIVE_UNASSIGNED"

class PacingDecisionType(str, Enum):
    APPROVED = "APPROVED"
    REDUCED = "REDUCED"
    REJECTED = "REJECTED"
    FALLBACK_TO_PROGRESSIVE = "FALLBACK_TO_PROGRESSIVE"

class EventClassification(str, Enum):
    VALID = "VALID"
    DUPLICATE = "DUPLICATE"
    LATE = "LATE"
    IMPOSSIBLE = "IMPOSSIBLE"
